// music-catalog.ts — SOURCE OF TRUTH for single-song + pick-N bundle sales (Howling Moon Music).
// SERVER-ONLY: this file holds the download URLs, so it lives under an underscore folder (GitHub Pages /
// Jekyll never serves "_" paths). The public picker list js/music-catalog.js (ids + titles, NO urls) is
// generated from this file by _tools/build-music-catalog.mjs — edit here, then re-run that script.
// Seeded 2026-10-03 from the 87 songs downloads/my-bundle.html offered (14 PuppySongs first, then the
// catalog minus the 6 hoisted duplicates), each url = the exact recording that page served.
// ROCK A BYE BABY: the old audio/rock-a-bye-baby.mp3 returned 400 (missing) -> repointed to the v55 album master.
// id = the song page slug (songs/<id>.html). Titles are ALL CAPS (brand law).
export interface CatalogSong { id: string; title: string; url: string }

export const MUSIC_CATALOG: CatalogSong[] = [
  { id: "will-you-be-my-friend", title: "WILL YOU BE MY FRIEND", url: "https://vwedcmdtsvktbirlgvdb.supabase.co/storage/v1/object/public/howls-music/WILL%20YOU%20BE%20MY%20FRIEND.wav" },
  { id: "trouble-trouble-pup", title: "TROUBLE TROUBLE PUP", url: "https://vwedcmdtsvktbirlgvdb.supabase.co/storage/v1/object/public/howls-music/Trouble%20Trouble%20Pup.wav" },
  { id: "uh-oh-i-did-it-again", title: "UH OH I DID IT AGAIN", url: "https://vwedcmdtsvktbirlgvdb.supabase.co/storage/v1/object/public/howls-music/Zoomies%20In%20The%20House.wav" },
  { id: "spurs", title: "SPURS", url: "https://vwedcmdtsvktbirlgvdb.supabase.co/storage/v1/object/public/howls-music/Spurs.mp3" },
  { id: "puppy-kisses", title: "PUPPY KISSES", url: "https://vwedcmdtsvktbirlgvdb.supabase.co/storage/v1/object/public/howls-music/Puppy%20Kisses.wav" },
  { id: "booty-boom-boom", title: "BOOTY BOOM BOOM", url: "https://vwedcmdtsvktbirlgvdb.supabase.co/storage/v1/object/public/howls-music/Booty%20Boom%20Boom.wav" },
  { id: "fleas", title: "FLEAS", url: "https://vwedcmdtsvktbirlgvdb.supabase.co/storage/v1/object/public/howls-music/FLEAS.wav" },
  { id: "hungry-eyes", title: "HUNGRY EYES", url: "https://vwedcmdtsvktbirlgvdb.supabase.co/storage/v1/object/public/howls-music/HUNGRY%20EYES%20(1).wav" },
  { id: "im-begging-you", title: "I'M BEGGING YOU", url: "https://vwedcmdtsvktbirlgvdb.supabase.co/storage/v1/object/public/howls-music/I'm%20Begging%20You.wav" },
  { id: "look-in-my-eyes", title: "LOOK IN MY EYES", url: "https://vwedcmdtsvktbirlgvdb.supabase.co/storage/v1/object/public/howls-music/Look%20in%20My%20Eyes.wav" },
  { id: "my-bed-aint-mine", title: "MY BED AIN'T MINE", url: "https://vwedcmdtsvktbirlgvdb.supabase.co/storage/v1/object/public/howls-music/My%20Bed%20Aint%20Mine.wav" },
  { id: "drown-me-in-slobbery-kisses", title: "DROWN ME IN SLOBBERY KISSES", url: "https://vwedcmdtsvktbirlgvdb.supabase.co/storage/v1/object/public/howls-music/Drown%20Me%20in%20Slobbery%20Kisses.wav" },
  { id: "christmas-puppy", title: "PUPPY CHRISTMAS", url: "https://vwedcmdtsvktbirlgvdb.supabase.co/storage/v1/object/public/howls-music/Puppy%20Christmas.wav" },
  { id: "slobbery-kiss", title: "SLOBBERY KISS", url: "https://vwedcmdtsvktbirlgvdb.supabase.co/storage/v1/object/public/howls-music/SLOBBERY%20KISS%20.wav" },
  // 2026-10-03: three PuppyFM station songs that had no single/bundle entry — full-length tracks
  // (BROWN EYES SAY = the GHOST WANTED DEAD OR ALIVE album master; the other two = the files the UNLEASHED album delivers).
  { id: "dogs-have-never", title: "DOGS HAVE NEVER", url: "https://vwedcmdtsvktbirlgvdb.supabase.co/storage/v1/object/public/howls-music/Dogs%20Have%20Never.mp3" },
  { id: "brown-eyes-say", title: "BROWN EYES SAY", url: "https://vwedcmdtsvktbirlgvdb.supabase.co/storage/v1/object/public/howls-music/v55/GHOST-WANTED-DEAD-OR-ALIVE/12-BROWN-EYES-SAY.mp3" },
  { id: "those-big-brown-eyes", title: "THOSE BIG BROWN EYES", url: "https://vwedcmdtsvktbirlgvdb.supabase.co/storage/v1/object/public/howls-music/Those%20Big%20Brown%20Eyes.mp3" },
  { id: "almost-called", title: "ALMOST CALLED", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/BEACH%20VIBES/NEW%20MEXICO%20SONGS/Untitled%20folder/SAD%20SONGS%20GRIEF%20TEARS/Almost%20called%20(1).mp3" },
  { id: "barefoot-beach-beauty", title: "BAREFOOT BEACH BEAUTY", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/BAREFOOT%20BEACH%20BEAUTY%20(2).mp3" },
  { id: "bigfoot-lives-here", title: "BIGFOOT LIVES HERE", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Bigfoot%20Lives%20Here%20_%20Bigfoot%20Leonberger%20Ranch%20Anthem.mp3" },
  { id: "breathe", title: "BREATHE", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/BEACH%20VIBES/Breathe.mp3" },
  { id: "coconut-kiss", title: "COCONUT KISS", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/COCONUT%20KISS%20(MASTER).mp3" },
  { id: "coffee-constellation", title: "COFFEE CONSTELLATION", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/coffee-constellation.mp3" },
  { id: "cotton-candy", title: "COTTON CANDY", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/COTTON%20CANDY%20(1).mp3" },
  { id: "crack-the-sky", title: "CRACK THE SKY", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Crack%20the%20sky.wav" },
  { id: "crackhead-queen", title: "CRACKHEAD QUEEN", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/crackhead-queen.mp3" },
  { id: "daddys-eyes", title: "DADDY'S EYES", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/BEACH%20VIBES/MUSIC%20ALBUM%20REDLIPSTICK%20%26%20BUSTED%20KNUCKLES%20COLLECTION/DADDY'S%20EYES%20%20(1).wav" },
  { id: "dont-cry-at-my-funeral", title: "DON'T CRY AT MY FUNERAL", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Don_t%20cry%20%20(1).wav" },
  { id: "down-under", title: "DOWN UNDER", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/DOWN%20UNDER.mp3" },
  { id: "drown-in-the-bottle", title: "DROWN IN THE BOTTLE", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/Drown%20in%20the%20bottle%20(1).mp3" },
  { id: "drowning-in-my-tears", title: "DROWNING IN MY TEARS", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/BEACH%20VIBES/NEW%20MEXICO%20SONGS/Untitled%20folder/SAD%20SONGS%20GRIEF%20TEARS/Drowning%20in%20my%20tears%20(Cover).mp3" },
  { id: "enchanted-green-haze", title: "ENCHANTED GREEN HAZE", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/BEACH%20VIBES/NEW%20MEXICO%20SONGS/Enchanted%20Green%20Haze.mp3" },
  { id: "endless-summer", title: "ENDLESS SUMMER", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/Endless%20Summer%20Heat%20(Cover).mp3" },
  { id: "favorite-mistake", title: "FAVORITE MISTAKE", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/BEACH%20VIBES/MUSIC%20ALBUM%20VILLAIN%202025/Favorite%20Mistake%20.wav" },
  { id: "fields-of-gold", title: "FIELDS OF GOLD", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/BEACH%20VIBES/MUSIC%20ALBUM%20RAINBOW%202025/Fields%20of%20Gold%20%20.wav" },
  { id: "fire-from-heaven", title: "FIRE FROM HEAVEN", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/Fire%20from%20Heaven.mp3" },
  { id: "fireflies-and-fireworks", title: "FIREFLIES & FIREWORKS", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/BEACH%20VIBES/MUSIC%20ALBUM%20RAINBOW%202025/FIREFLYS%20%26%20FIREWORKS%20(1).wav" },
  { id: "floating", title: "FLOATING", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/Floating%20(2).mp3" },
  { id: "gaslight-and-glitter", title: "GASLIGHT & GLITTER", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/BEACH%20VIBES/GASLIGHT%20%26%20GLITTER.mp3" },
  { id: "ghost-wanted-dead-or-alive", title: "GHOST WANTED DEAD OR ALIVE", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/OUTLAW%20WESTERN%20ALBUM/Ghost%20Wanted%20Dead%20or%20Alive%20(1).mp3" },
  { id: "good-to-me", title: "GOOD TO ME", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/BEACH%20VIBES/MUSIC%20ALBUM%20VILLAIN%202025/GOOD%20TO%20ME.wav" },
  { id: "goodnight-baby", title: "GOODNIGHT BABY", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/BEACH%20VIBES/NEW%20MEXICO%20SONGS/goodnight-baby.mp3" },
  { id: "hazy-bubble", title: "HAZY BUBBLE", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/BEACH%20VIBES/NEW%20MEXICO%20SONGS/Untitled%20folder/SAD%20SONGS%20GRIEF%20TEARS/Hazy%20bubble.mp3" },
  { id: "held-you-first", title: "HELD YOU FIRST", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/Held%20you%20first%20(1).mp3" },
  { id: "i-aint-picking-up-your-shit-no-more", title: "I AIN'T PICKING UP YOUR SHIT NO MORE", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/I%20Ain't%20Picking%20Up%20Your%20Shhh..it!.mp3" },
  { id: "i-didnt-die", title: "I DIDN'T DIE", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/OUTLAW%20WESTERN%20ALBUM/I%20DIDN_T%20DIE%20(1).mp3" },
  { id: "if-tears-could-call-heaven", title: "IF TEARS COULD CALL HEAVEN", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/BEACH%20VIBES/NEW%20MEXICO%20SONGS/Untitled%20folder/SAD%20SONGS%20GRIEF%20TEARS/If%20tears%20could%20call%20heaven%20(Cover).mp3" },
  { id: "invisible-woman", title: "INVISIBLE WOMAN", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/OUTLAW%20WESTERN%20ALBUM/Invisible%20woman%20(1).mp3" },
  { id: "keep-pushing-me", title: "KEEP PUSHING ME", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Keep%20pushing%20me%20(1).wav" },
  { id: "kick-your-ass", title: "KICK YOUR ASS", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/BEACH%20VIBES/Kick%20your%20ass%20(Remastered).wav" },
  { id: "las-cruces-nights", title: "LAS CRUCES NIGHTS", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/BEACH%20VIBES/NEW%20MEXICO%20SONGS/Las%20Cruces%20Nights.mp3" },
  { id: "left-my-heart-in-santa-fe", title: "LEFT MY HEART IN SANTA FE", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/Left%20my%20heart%20in%20Santa%20Fe.mp3" },
  { id: "liar-preacher-man", title: "LIAR, PREACHER MAN", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/LIAR%2C%20PREACHER%20MAN%20(1).mp3" },
  { id: "lightning-strikes", title: "LIGHTNING STRIKES", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/LIGHTNING%20STRIKES%20MY%20HEART.mp3" },
  { id: "looking-for-my-swagger", title: "LOOKING FOR MY SWAGGER", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/Looking%20for%20My%20Swagger%20(Edit)%20(1).mp3" },
  { id: "lost-in-santa-fe", title: "LOST IN SANTA FE", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/Lost%20in%20Santa%20Fe.mp3" },
  { id: "love-me-complicated", title: "LOVE ME COMPLICATED", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/Love%20me%20complicated%20(1).mp3" },
  { id: "mangroves-and-moonlight", title: "MANGROVES & MOONLIGHT", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/Mangroves%20%26%20Moonlight.mp3" },
  { id: "mi-hogar", title: "MI HOGAR", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/BEACH%20VIBES/Mi%20Hogar%2C%20My%20Home.mp3" },
  { id: "never-let-go", title: "NEVER LET GO / HAND IN HAND", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/NEVER%20LET%20GO%20(master).mp3" },
  { id: "not-enough-bottles", title: "NOT ENOUGH BOTTLES", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/BEACH%20VIBES/NEW%20MEXICO%20SONGS/Untitled%20folder/SAD%20SONGS%20GRIEF%20TEARS/Not%20Enough%20Bottles.mp3" },
  { id: "still-obsessed", title: "OBSESSED", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/BEACH%20VIBES/still-obsessed.mp3" },
  { id: "one-night-with-the-devil", title: "ONE NIGHT WITH THE DEVIL", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/OUTLAW%20WESTERN%20ALBUM/One%20night%20with%20the%20devil%20(1).mp3" },
  { id: "only-gift-i-need", title: "ONLY GIFT I NEED", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/BEACH%20VIBES/the-only-gift-i-need.mp3" },
  { id: "paper-soldier", title: "PAPER SOLDIER", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/Paper%20Soldier%20(1).mp3" },
  { id: "port-lavaca-paradise", title: "PORT LAVACA PARADISE", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/PORT%20LAVACA.mp3" },
  { id: "puff-planet", title: "PUFF PLANET", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/BEACH%20VIBES/MUSIC%20ALBUM%20RAINBOW%202025/PUFF%20%20planet%20(1).wav" },
  { id: "pussy-juice", title: "PUSSY JUICE", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/BEACH%20VIBES/pussy-juice.mp3" },
  { id: "rainbow", title: "RAINBOW", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/BEACH%20VIBES/rainbow.mp3" },
  { id: "ride-or-die", title: "RIDE OR DIE", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/RIDE%20OR%20DIE.wav" },
  { id: "rock-a-bye-baby", title: "ROCK A BYE BABY", url: "https://vwedcmdtsvktbirlgvdb.supabase.co/storage/v1/object/public/howls-music/v55/SONGS-TO-CRY-TO/04-ROCK-A-BYE-BABY.mp3" },
  { id: "rodeo-cowboy", title: "RODEO COWBOY", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/OUTLAW%20WESTERN%20ALBUM/RODEO%20COWBOY%20(EDIT)%20(Edit)%20(1).mp3" },
  { id: "sand-in-toes", title: "SAND IN TOES", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/Sand%20in%20Toes%20(1).mp3" },
  { id: "silence-is-your-fangs", title: "SILENCE IS YOUR FANGS", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/SILENCE%20IS%20YOUR%20FANGS%20(1).mp3" },
  { id: "sleep", title: "SLEEP", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/Sleep%20(2).mp3" },
  { id: "smoke-me", title: "SMOKE ME", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/OUTLAW%20WESTERN%20ALBUM/SMOKE%20ME%20(1).mp3" },
  { id: "stage-4-liabetes", title: "STAGE 4 LIABETES", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/BEACH%20VIBES/Liabetes%20(Remastered)%20(1).wav" },
  { id: "still-the-asshole", title: "STILL THE ASSHOLE", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/BEACH%20VIBES/still-the-asshole.mp3" },
  { id: "tangled", title: "TANGLED", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/TANGLED%20(MASTER).mp3" },
  { id: "tattoo-in-albuquerque", title: "TATTOO IN ALBUQUERQUE", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/BEACH%20VIBES/NEW%20MEXICO%20SONGS/Tattoo.mp3" },
  { id: "tear-drops-in-my-coffee", title: "TEAR DROPS IN MY COFFEE", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/Tear%20drops%20in%20my%20coffee.mp3" },
  { id: "this-is-shame", title: "THIS IS SHAME", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/BEACH%20VIBES/MUSIC%20ALBUM%20REDLIPSTICK%20%26%20BUSTED%20KNUCKLES%20COLLECTION/This%20is%20Shame%20(2).wav" },
  { id: "tongue-and-groove", title: "TONGUE & GROOVE", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/BEACH%20VIBES/Tongue%20%26%20Groove.mp3" },
  { id: "twinkle", title: "TWINKLE TWINKLE LITTLE BITCH (JT)", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/twinkle.mp3" },
  { id: "uncontainable", title: "UNCONTAINABLE", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/Uncontainable%20(1).mp3" },
  { id: "villain", title: "VILLAIN", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/BEACH%20VIBES/villian-(add-vocal)%20vs1.mp3" },
  { id: "when-you-wake", title: "WHEN YOU WAKE", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/BEACH%20VIBES/when-you-wake.mp3" },
  { id: "woke-up-laughing", title: "WOKE UP LAUGHING", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/Woke%20Up%20Laughing%20(1).mp3" },
  { id: "world-melts-away", title: "WORLD MELTS AWAY", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/WORLD%20MELTS%20AWAY.mp3" },
  { id: "zero-rips-left", title: "ZERO RIPS LEFT", url: "https://pxcxtnabyydhbfbholvh.supabase.co/storage/v1/object/public/audio/Album%20Collections/BEACH%20VIBES/zero-rips-left.mp3" },
];

// The PuppySongs | PuppyFM (14 + 3 added 2026-10-03) — listed first in the picker under their own heading (and alone with ?pack=puppy).
export const PUPPY_SONG_IDS: string[] = ["will-you-be-my-friend","trouble-trouble-pup","uh-oh-i-did-it-again","spurs","puppy-kisses","booty-boom-boom","fleas","hungry-eyes","im-begging-you","look-in-my-eyes","my-bed-aint-mine","drown-me-in-slobbery-kisses","christmas-puppy","slobbery-kiss","dogs-have-never","brown-eyes-say","those-big-brown-eyes"];
